### ISSUE TITLE
StreamReader introduces reserved name `streamId`

### ISSUE THREAD

**Issue by AngusP** [RedisLabsModules/RedisGears#115]
From the Streaming API example:

> It is also possible to register on streams using the following syntax:
> 
> `GearsBuilder('StreamReader').foreach(lambda x: execute('set', x['streamId'], str(x))).register('s1')`
> 
> This execution will be trigger for each new record that enter stream s1
> 
> The format of the records that arrive from the stream reader is:
> 
> `{'streamId': '<stream-id>', <field1>:<value1>, <field2>:<value2>, ...}`

This introduces `streamId` as a special reserved name, such that a stream with a field of the same name, e.g. `XADD s1 * streamId asdf`, the value `asdf` would surely either get overwritten with `<stream-id>` or cause breakage? (I've not been able to check actual behaviour yet)

The more 'pythonic' thing is perhaps for the `x`es to be a class that extends `dict` rather than vanilla Python `dicts`, so that `x['streamId']` would be whatever got `XADD`ed, and `x.streamId` is the actual ID. Alternatively, you could add a level to the structure:

```
{'streamId': '<stream-id>', 'fields': {<field1>:<value1>, <field2>:<value2>, ...}}
```

Happy to poke around and try address this, but not yet familiar with the RedisGears codebase...

**Comment by itamarhaber** [comment]
Hello @AngusP 

This is essentially what is planned for addressing #46 - I agree that 'streamId' is not consistent with existing Redis Streams terminology.

**Comment by K-Jo** [comment]
@AngusP can we close the issue and further track this in #46?  We plan to make this part of our 1.0 GA release

**Comment by AngusP** [comment]
@K-Jo Sure, sounds good :smile:
